/**
 * This file is used as a fallback data on an API request failure.
 */

export const KNOWN_MEMBERS = [
    {
      "login": "LaurenceM10",
      "id": 13529689,
      "node_id": "MDQ6VXNlcjEzNTI5Njg5",
      "avatar_url": "https://avatars1.githubusercontent.com/u/13529689?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/LaurenceM10",
      "html_url": "https://github.com/LaurenceM10",
      "followers_url": "https://api.github.com/users/LaurenceM10/followers",
      "following_url": "https://api.github.com/users/LaurenceM10/following{/other_user}",
      "gists_url": "https://api.github.com/users/LaurenceM10/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/LaurenceM10/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/LaurenceM10/subscriptions",
      "organizations_url": "https://api.github.com/users/LaurenceM10/orgs",
      "repos_url": "https://api.github.com/users/LaurenceM10/repos",
      "events_url": "https://api.github.com/users/LaurenceM10/events{/privacy}",
      "received_events_url": "https://api.github.com/users/LaurenceM10/received_events",
      "type": "User",
      "site_admin": false
    },
    {
      "login": "amosrivera",
      "id": 548232,
      "node_id": "MDQ6VXNlcjU0ODIzMg==",
      "avatar_url": "https://avatars1.githubusercontent.com/u/548232?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/amosrivera",
      "html_url": "https://github.com/amosrivera",
      "followers_url": "https://api.github.com/users/amosrivera/followers",
      "following_url": "https://api.github.com/users/amosrivera/following{/other_user}",
      "gists_url": "https://api.github.com/users/amosrivera/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/amosrivera/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/amosrivera/subscriptions",
      "organizations_url": "https://api.github.com/users/amosrivera/orgs",
      "repos_url": "https://api.github.com/users/amosrivera/repos",
      "events_url": "https://api.github.com/users/amosrivera/events{/privacy}",
      "received_events_url": "https://api.github.com/users/amosrivera/received_events",
      "type": "User",
      "site_admin": false
    },
    {
      "login": "christopher-ramirez",
      "id": 1440398,
      "node_id": "MDQ6VXNlcjE0NDAzOTg=",
      "avatar_url": "https://avatars1.githubusercontent.com/u/1440398?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/christopher-ramirez",
      "html_url": "https://github.com/christopher-ramirez",
      "followers_url": "https://api.github.com/users/christopher-ramirez/followers",
      "following_url": "https://api.github.com/users/christopher-ramirez/following{/other_user}",
      "gists_url": "https://api.github.com/users/christopher-ramirez/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/christopher-ramirez/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/christopher-ramirez/subscriptions",
      "organizations_url": "https://api.github.com/users/christopher-ramirez/orgs",
      "repos_url": "https://api.github.com/users/christopher-ramirez/repos",
      "events_url": "https://api.github.com/users/christopher-ramirez/events{/privacy}",
      "received_events_url": "https://api.github.com/users/christopher-ramirez/received_events",
      "type": "User",
      "site_admin": false
    },
    {
      "login": "hosmelq",
      "id": 1166143,
      "node_id": "MDQ6VXNlcjExNjYxNDM=",
      "avatar_url": "https://avatars2.githubusercontent.com/u/1166143?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/hosmelq",
      "html_url": "https://github.com/hosmelq",
      "followers_url": "https://api.github.com/users/hosmelq/followers",
      "following_url": "https://api.github.com/users/hosmelq/following{/other_user}",
      "gists_url": "https://api.github.com/users/hosmelq/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/hosmelq/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/hosmelq/subscriptions",
      "organizations_url": "https://api.github.com/users/hosmelq/orgs",
      "repos_url": "https://api.github.com/users/hosmelq/repos",
      "events_url": "https://api.github.com/users/hosmelq/events{/privacy}",
      "received_events_url": "https://api.github.com/users/hosmelq/received_events",
      "type": "User",
      "site_admin": false
    },
    {
      "login": "jarbitlira",
      "id": 3398354,
      "node_id": "MDQ6VXNlcjMzOTgzNTQ=",
      "avatar_url": "https://avatars1.githubusercontent.com/u/3398354?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/jarbitlira",
      "html_url": "https://github.com/jarbitlira",
      "followers_url": "https://api.github.com/users/jarbitlira/followers",
      "following_url": "https://api.github.com/users/jarbitlira/following{/other_user}",
      "gists_url": "https://api.github.com/users/jarbitlira/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/jarbitlira/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/jarbitlira/subscriptions",
      "organizations_url": "https://api.github.com/users/jarbitlira/orgs",
      "repos_url": "https://api.github.com/users/jarbitlira/repos",
      "events_url": "https://api.github.com/users/jarbitlira/events{/privacy}",
      "received_events_url": "https://api.github.com/users/jarbitlira/received_events",
      "type": "User",
      "site_admin": false
    },
    {
      "login": "jenniercruz",
      "id": 25697290,
      "node_id": "MDQ6VXNlcjI1Njk3Mjkw",
      "avatar_url": "https://avatars1.githubusercontent.com/u/25697290?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/jenniercruz",
      "html_url": "https://github.com/jenniercruz",
      "followers_url": "https://api.github.com/users/jenniercruz/followers",
      "following_url": "https://api.github.com/users/jenniercruz/following{/other_user}",
      "gists_url": "https://api.github.com/users/jenniercruz/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/jenniercruz/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/jenniercruz/subscriptions",
      "organizations_url": "https://api.github.com/users/jenniercruz/orgs",
      "repos_url": "https://api.github.com/users/jenniercruz/repos",
      "events_url": "https://api.github.com/users/jenniercruz/events{/privacy}",
      "received_events_url": "https://api.github.com/users/jenniercruz/received_events",
      "type": "User",
      "site_admin": false
    },
    {
      "login": "juanpicado",
      "id": 558752,
      "node_id": "MDQ6VXNlcjU1ODc1Mg==",
      "avatar_url": "https://avatars0.githubusercontent.com/u/558752?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/juanpicado",
      "html_url": "https://github.com/juanpicado",
      "followers_url": "https://api.github.com/users/juanpicado/followers",
      "following_url": "https://api.github.com/users/juanpicado/following{/other_user}",
      "gists_url": "https://api.github.com/users/juanpicado/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/juanpicado/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/juanpicado/subscriptions",
      "organizations_url": "https://api.github.com/users/juanpicado/orgs",
      "repos_url": "https://api.github.com/users/juanpicado/repos",
      "events_url": "https://api.github.com/users/juanpicado/events{/privacy}",
      "received_events_url": "https://api.github.com/users/juanpicado/received_events",
      "type": "User",
      "site_admin": false
    },
    {
      "login": "leftdevel",
      "id": 843337,
      "node_id": "MDQ6VXNlcjg0MzMzNw==",
      "avatar_url": "https://avatars3.githubusercontent.com/u/843337?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/leftdevel",
      "html_url": "https://github.com/leftdevel",
      "followers_url": "https://api.github.com/users/leftdevel/followers",
      "following_url": "https://api.github.com/users/leftdevel/following{/other_user}",
      "gists_url": "https://api.github.com/users/leftdevel/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/leftdevel/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/leftdevel/subscriptions",
      "organizations_url": "https://api.github.com/users/leftdevel/orgs",
      "repos_url": "https://api.github.com/users/leftdevel/repos",
      "events_url": "https://api.github.com/users/leftdevel/events{/privacy}",
      "received_events_url": "https://api.github.com/users/leftdevel/received_events",
      "type": "User",
      "site_admin": false
    },
    {
      "login": "oscarmcm",
      "id": 2553459,
      "node_id": "MDQ6VXNlcjI1NTM0NTk=",
      "avatar_url": "https://avatars3.githubusercontent.com/u/2553459?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/oscarmcm",
      "html_url": "https://github.com/oscarmcm",
      "followers_url": "https://api.github.com/users/oscarmcm/followers",
      "following_url": "https://api.github.com/users/oscarmcm/following{/other_user}",
      "gists_url": "https://api.github.com/users/oscarmcm/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/oscarmcm/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/oscarmcm/subscriptions",
      "organizations_url": "https://api.github.com/users/oscarmcm/orgs",
      "repos_url": "https://api.github.com/users/oscarmcm/repos",
      "events_url": "https://api.github.com/users/oscarmcm/events{/privacy}",
      "received_events_url": "https://api.github.com/users/oscarmcm/received_events",
      "type": "User",
      "site_admin": false
    },
    {
      "login": "paulomcnally",
      "id": 181533,
      "node_id": "MDQ6VXNlcjE4MTUzMw==",
      "avatar_url": "https://avatars2.githubusercontent.com/u/181533?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/paulomcnally",
      "html_url": "https://github.com/paulomcnally",
      "followers_url": "https://api.github.com/users/paulomcnally/followers",
      "following_url": "https://api.github.com/users/paulomcnally/following{/other_user}",
      "gists_url": "https://api.github.com/users/paulomcnally/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/paulomcnally/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/paulomcnally/subscriptions",
      "organizations_url": "https://api.github.com/users/paulomcnally/orgs",
      "repos_url": "https://api.github.com/users/paulomcnally/repos",
      "events_url": "https://api.github.com/users/paulomcnally/events{/privacy}",
      "received_events_url": "https://api.github.com/users/paulomcnally/received_events",
      "type": "User",
      "site_admin": false
    }
  ]
